TARGET  := alertcenter.exe
INCS = -I ../network -I ../utils -I ../depends
LIBS = -L ../utils -lutils -L ../network -lnetwork -Wl,-Bstatic -Wl,-Bdynamic -lm -lev -lhiredis -ljansson -lmpdec -lcurl -lssl -lcrypto
include ../makefile.inc
